'''
To calculate the LTV per investor, we need to know the revenue generated by each investor (property) and the estimated 
lifespan of each investor (property). We can assume that the revenue generated by an investor is the sum of the monthly 
rent collected over the estimated lifespan of the investor.

To estimate the lifespan of an investor (property), we can use the Kaplan-Meier estimator to estimate the survival function, 
and then find the median survival time. This will give us an estimate of how long, on average, 
an investor (property) stays with us before churning.
'''

import sqlite3
import pandas as pd
import numpy as np
from lifelines import KaplanMeierFitter

# Connect to database and load data into pandas dataframes
conn = sqlite3.connect('mynd.db')
properties = pd.read_sql_query('SELECT * FROM properties', conn)
contracts = pd.read_sql_query('SELECT * FROM contracts', conn)

# Calculate revenue generated by each property
properties['revenue'] = contracts.groupby('property_id')['rent'].sum()

# Fit Kaplan-Meier estimator to estimate survival function
kmf = KaplanMeierFitter()
kmf.fit(properties['offboard_date'] - properties['onboard_date'])
median_survival_time = kmf.median_survival_time_

# Calculate LTV per investor
properties['ltv'] = properties['revenue'] * median_survival_time

# Print results
print(properties[['property_id', 'revenue', 'ltv']])
